### PR TITLE
Filter city on volunteer form

### PR DESCRIPTION
**Pull request by Alirezabg**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

- **Purpose** - 
Filter city on the volunteer form where volunteer signup

should only get available cities in volunteer form

### Links

Task: CodeYourFuture/tech-team#597
API PR: CodeYourFuture/cyf-api#499

### Author checklist

- [ ] I have written a title that reflects the relevant ticket
- [ ] I have written a description that says what the PR does and how to validate it
- [ ] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [ ] I have added a link to this PR to the ticket
- [ ] I have made the PR to `staging` from a branch named `<category>/<name>`, e.g. `feature/edit-spaceships` or `bugfix/restore-oxygen`

### Reviewer checklist
Remember that asking questions helps everyone understand why decisions have been made, so the next person can see too!
- **Pull request** - read the content of the PR itself (_Conversation_ tab) and consider the following questions:
    - Is the user story/ticket linked?
    - Does the description match the linked item?
    - Does the description tell you how to validate the work?
    - Does the build still work (_Checks_ tab)?
    - What approach would you take to meet this goal?
- **Code changes** - read through the changeset (_Files changed_ tab) and consider the following questions:
    - Do the code changes match the description?
    - Are there any changes that should not be part of this pull request (e.g. layout changes in files not related to the functionality)?
    - Do you understand what the changes are doing, how they meet the goal of the PR?
    - Does the approach to meeting those goals seem sensible? If it's not the one you thought of, is it significantly better or worse?
    - Is this well-structured code (consistent layout, comprehensible variable names, relatively small files)?
- **Software** - check out the PR branch, run the software and consider the following questions:
    - Does the product still start and run correctly?
    - Is the goal of the pull request met (i.e. new behaviour for a new feature, changed behaviour for a bug fix, identical behaviour for a refactor)?
    - In the parts of the product this PR touched:
        - Is the spelling, punctuation and grammar for user-facing text correct?
        - Does the layout/UI match the designs?
- **Project progress**
    - Have new tickets been created to cover any additional actions that have appeared during this review?

### CODE REVIEW

**Review by MarkFarmiloe — APPROVED** [review]
Looks fine

**Review by MarinaAlmeida20 — APPROVED** [review]
Looks good to me

**Review by Bondcoder — APPROVED** [review]
LGTM! 🚀 

I left comments on the other PR: https://github.com/CodeYourFuture/cyf-api/pull/499#pullrequestreview-1137871015

**Comment by MarinaAlmeida20** [comment]
When I run locally the API and run dashboard. Go to Dashboard/Cities and edit one of the cities to not show in the Volunteer Application Form for example and check it, it's not appears any more into Volunteer Application Form. It also works.

**Pull request merged**
