### PR TITLE
Feature/697-move-employer-names-to-backend-code-rever-all-changes-merged-to-qa-branch[QA]

### PR DESCRIPTION
**Pull request by khmdagal**
This is a:

- [ ] ✨ **New feature** - new behaviour has been implemented
- [x] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

**Purpose**
This PR aims to revert all the changes merged to the QA branch. In other words, bringing back where the QA branch was before this implementation.

**How to check** 

1. Visit this branch: **feature/697-move-employer-names-to-backend-code**.
2. Run cyf-api repo.
3. Run your cyf-forms repo, when the form loads you should be able to see all the employers' names. The employers' list is coming from the front-end code.

**Links**
issue: https://github.com/CodeYourFuture/tech-team/issues/697
cyf-api:  https://github.com/CodeYourFuture/cyf-api/pull/635

### Author checklist

- [x] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [x] I have made the PR to `qa` from a branch named **feature/697-move-employer-names-to-backend-code**.
- [x] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#manual-test-procedures)
- [x] I have requested reviewers here and in my team chat channel

- [x] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [x] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

### CODE REVIEW

**Review by ChidimmaOfodum — CHANGES_REQUESTED** [review]
Tests are passing and relevant to the task. Form is fetching employee data from the modified source. Form works as expected. 

This branch is from QA too. Rebase to staging.

**Comment by khmdagal** [comment]
> Tests are passing and relevant to the task. Form is fetching employee data from the modified source. Form works as expected.
> 
> This branch is from QA too. Rebase to staging.

This will revert the changes that have already been merged to the qa. Thanks

**Review by ChidimmaOfodum — APPROVED** [review]

**Review by ChidimmaOfodum — CHANGES_REQUESTED** [review]
There is still one more change on e2e/integration/journey.test.js line 124 - the original code was ==cy.findByRole('combobox', { name: /who is your employer/i }).type(
    'Cap{enter}'
  )==

**Comment by khmdagal** [comment]
> There is still one more change on e2e/integration/journey.test.js line 124 - the original code was `cy.findByRole('combobox', { name: /who is your employer/i }).type( 'Cap{enter}' )`

The assertion looks like 'Capgemini'; to have the current behaviour, it should be **type( 'Capgemini{enter}')**  as **Cap is not Capgemini**.  Hope that helps.

**Review by ChidimmaOfodum — DISMISSED** [review]

**Review by CanaryWharf — CHANGES_REQUESTED** [review]
> > There is still one more change on e2e/integration/journey.test.js line 124 - the original code was `cy.findByRole('combobox', { name: /who is your employer/i }).type( 'Cap{enter}' )`
> 
> The assertion wants 'Capgemini'; to have the current behaviour, it should be **type( 'Capgemini{enter}')** as **Cap is not Capgemini**. Hope that helps.

Regardless of whether it should be. When reverting changes, you should undo all changes at is was made. Any future fixes should be in a different PR.
Ideally, a revert should be made by going back to the actual PR page and clicking "Revert"

**Review by CanaryWharf — APPROVED** [review]

**Pull request merged**
