### PR TITLE
Volunteer-team-preference [ Master ]

### PR DESCRIPTION
**Pull request by H-BAHDON**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

Purpose -
The purpose of this ticket is to enable CYF Staff members to streamline the onboarding process by requesting volunteers to identify the specific team they would like to volunteer for during the sign-up process, this will accelerating the overall onboarding procedure.

How to check -

Verify that the list is displaying all the teams {Education, Mentorship, Outreach, Personal Development, Tech Project} in alphabetical order.

Create a new team in the MongoDB under the "teams" section. You can accomplish this by cloning one of the existing teams and changing its name to "New Team."

Check the form to ensure that the newly created team ("New Team") is added as an option.

Navigate to the dashboard at /volunteers and confirm that the "New Team" is correctly added to the teams list.

Select one user from the dashboard and modify their team assignment, changing it to the newly created "New Team."

Delete the "New Team" you have created from the MongoDB.

After deleting the "New Team," verify that the dashboard for the selected user automatically updates to display "Select Team" as the option.

### Author checklist

- [x] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [x] I have made the PR to `qa` from a branch named `<category>/<name>`, e.g. `feature/edit-spaceships` or `bugfix/restore-oxygen`
- [x] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#manual-test-procedures)
- [x] I have requested reviewers here and in my team chat channel

- [x] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [x] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

### CODE REVIEW

**Comment by SaadiaELF** [comment]
@H-BAHDON can you modify the PR title to reflect the purpose of the PR

**Review by SaadiaELF — APPROVED** [review]
I have tested all the existing scenarios + created new volunteers using then form + tested related filters, all LGFM

**Comment by textbook** [comment]
+1 for changing the title, looking at https://github.com/CodeYourFuture/cyf-forms/pulls?q=is%3Apr+base%3Amaster should make any programmer feel itchy!

**Review by AliNurisiahsiahi — APPROVED** [review]
It [worked](https://docs.google.com/spreadsheets/d/1oMjdAJ3Ghw5JHd1LShx24dRjnFjSB9pvXg2yarJTg8A/edit#gid=1433784011) as I expected. I created a new team and it appeared in the list in alphabetic order.

Create new team
Screenshot 2023-09-06 at 11 25 25

Appear in the form
Screenshot 2023-09-06 at 11 18 48

Appeared in dashboard
Screenshot 2023-09-06 at 11 21 23

Delete team
Screenshot 2023-09-06 at 11 25 50
Screenshot 2023-09-06 at 11 25 58
Disappeared in the form and dashboard
Screenshot 2023-09-06 at 11 27 45
Screenshot 2023-09-06 at 11 29 24

**Comment by KhesiweDube** [comment]
Tested all the scenarios are working as [expected](https://docs.google.com/spreadsheets/d/1I2HC75gY-l5TqIXbzo-VfKzanSVD-gufedGZwkHEHKQ/edit?usp=sharing).
 
TeamsTest1

TeamsTest2

TeamsTest4

TeamsT5

**Review by KhesiweDube — APPROVED** [review]

**Pull request merged**
