### PR TITLE
Features/identify capgemini volunteers

### PR DESCRIPTION
**Pull request by MarkFarmiloe**
This is a:

- [x]  ✨ New feature - new behaviour has been implemented
- [ ]  🐛 Bug fix - existing behaviour has been made to behave
- [ ]  ♻️ Refactor - the behaviour has not changed, just the implementation
- [ ]  ✅ Test backfill - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ]  ⚙️ Chore - maintenance task, behaviour and implementation haven't changed
 

### Description
**Purpose** -
- Add a new drop-down to the form allowing users to choose their employer.

**How to check** -

- To observe the behaviour raised in issue #501
- Checkout the current staging branch
- In the cyf-forms project, run PORT=3002 yarn start.
- in the browser, visit http://localhost:3002/
- when users want to fill out the Volunteer Application Form they will be able to choose their employer with this menu
- Where did you hear about Code Your Future? *
- when Employer selected the new drop-down will appear with the employers
- after submitting the form user data will send to the back-end.

**Links**
[Identify volunteers that work for Capgemini #501](https://github.com/CodeYourFuture/tech-team/issues/501)
[Identify Capgemini Volunteers - fixes #501 #441](https://github.com/CodeYourFuture/cyf-api/pull/441)

**Author checklist**

- [x] I have written a title that reflects the relevant ticket
- [x]  I have written a description that says what the PR does and how to validate it
- [x]  I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x]  I have added a link to this PR to the ticket
- [x]  I have made the PR to staging from a branch named <category>/<name>, e.g. feature/edit-spaceships or bugfix/restore-oxygen
- [ ]  I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/Manual-Test-Procedures)
- [x]  I have requested reviewers here and in my team chat channel
- [ ]  I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [x]  I have added tests, or new tests were not required
- [x]  I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required
- [ ]  I have updated the Swagger API documentation in src/swagger/routes/
- [ ]  I have explicitly tested the access rights for at least unauthenticated, admin and non-admin cases

**Reviewer checklist**
Remember that asking questions helps everyone understand why decisions have been made, so the next person can see too!

- **Pull request** - read the content of the PR itself (Conversation tab) and consider the following questions:
- -  Is the user story/ticket linked?
- - Does the description match the linked item?
- - Does the description tell you how to validate the work?
- - Does the build still work (Checks tab)?
- - What approach would you take to meet this goal?

- **Code changes** - read through the changeset (Files changed tab) and consider the following questions:
- - Do the code changes match the description?
- - Are there any changes that should not be part of this pull request (e.g. layout changes in files not related to the functionality)?
- - Do you understand what the changes are doing, how they meet the goal of the PR?
- - Does the approach to meeting those goals seem sensible? If it's not the one you thought of, is it significantly better or worse?
- - Is this well-structured code (consistent layout, comprehensible variable names, relatively small files)?

- **Software** - check out the PR branch, run the software and consider the following questions:
- - Does the product still start and run correctly?
- - Is the goal of the pull request met (i.e. new behaviour for a new feature, changed behaviour for a bug fix, identical behaviour for a refactor)?
- - In the parts of the product this PR touched:
- - Is the spelling, punctuation and grammar for user-facing text correct?
- - Does the layout/UI match the designs?

- **Project progress**
- - Have new tickets been created to cover any additional actions that have appeared during this review?

### CODE REVIEW

**Comment by MarkFarmiloe** [comment]
@textbook 
Yes it works in QA
Yes they are the same changes.
Looking at the build failure - seems to be building using node v11.12.0. 
`error axe-core@4.4.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "11.12.0"`
There is no engine specified in the package.json and no lock file, so don't know how the build decided to use this version. I think I need advice.

**Comment by textbook** [comment]
> don't know how the build decided to use this version

https://github.com/CodeYourFuture/cyf-forms/blob/ef1e417b30a41c7ad6b891db245803a7fd3101e9/.circleci/config.yml#L28-L29

**Comment by MarkFarmiloe** [comment]
Now we know why it was building using that version.
But why is it configured to use that version and what do we do about it?

**Comment by textbook** [comment]
> why is it configured to use that version

I'm not sure what answer you're expecting! First-order answer is: because it was configured that way in e04ef20 and hasn't been updated since. Second-order answer appears to be: that was the [latest version](https://nodejs.org/en/download/releases/) of Node at that time (although not an LTS version, so arguably shouldn't have been used even then).

> what do we do about it

If `axe-core@4.4.2` doesn't work in Node 11, we have two (not mutually exclusive) choices: remove the incompatible dependency, or update Node. `axe-core` is a transitive dependency via `eslint-plugin-jsx-a11y`:

```
$ yarn why axe-core
yarn why v1.22.10
warning ../../../package.json: No license field
[1/4] 🤔  Why do we have the module "axe-core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "axe-core@4.3.2"
info Reasons this module exists
   - "eslint-plugin-jsx-a11y" depends on it
   - Hoisted from "eslint-plugin-jsx-a11y#axe-core"
```
so removing it entirely would have further consequences. Evidently at some point there was a version that _was_ compatible, so maybe we could look into pinning to that instead (this idea should seem familiar: CodeYourFuture/application-process#336).

And I doubt anyone in the team is actually working on this in Node 11, as [already suggested](https://codeyourfuture.slack.com/archives/C02FX4W0VM4/p1651314574942289) we should be moving off unsupported and potentially vulnerable Node versions (not so important here where it's at build time not run time, admittedly). One obvious step would be: aim for at least _consistency_ across this ecosystem, even if they're not all bang up-to-date.

---

Circling back:

> Yes it works in QA
> Yes they are the same changes

My point was more that these should be the **How to check**, that's what we're supposed to be reviewing for promotion, and _someone else_ should be validating that rather than just asserting it.

**Review by kfklein15 — APPROVED** [review]
This code was tested in QA and the employer came through correctly. The employer name (Capgemini or other) cannot be viewed on the Dashboard, but only on the Database. Rob confirming it was showing with the correct employer.

**Review by textbook — COMMENTED** [review]
This matches the changes introduced into QA in #80

**Review by textbook — APPROVED** [review]
Actually approving this time 🙈

**Review by kfklein15 — APPROVED** [review]
Approving this again. We changed the CI tests, not the code.

**Pull request merged**
