### PR TITLE
feature-765-add-iam-not-sure-option-to-the-volunteer-teams-question[STAGING]

### PR DESCRIPTION
**Pull request by khmdagal**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

Description
Purpose -
To allow new volunteers to choose the "I am not sure" option when choosing which team they want to join if they are not sure.

This ticket is a spin-off of https://github.com/CodeYourFuture/tech-team/issues/692

How it works and to check -

When a volunteer should see the "I am not sure" option in the drop-down menu.

The "I am not sure" option should be the last or bottom.

On the dashboard, it should show "Select team", If a new volunteer chooses the "I am not sure" option on the form.

Validation of this already included https://github.com/CodeYourFuture/tech-team/issues/692

Links
Ticket: https://github.com/CodeYourFuture/tech-team/issues/765

### Author checklist

- [x] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [ ] I have added a link to this PR to the ticket
- [ ] I have made the PR to **`stagging`** from a branch named  **`feature-765-add-iam-not-sure-option-to-the-volunteer-teams-question`**
- [ ] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#manual-test-procedures)
- [x] I have requested reviewers here and in my team chat channel

- [ ] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [ ] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

### CODE REVIEW

**Comment by SaadiaELF** [comment]
@khmdagal can you please make the PR title match the [ standards ](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#tips-to-create-good-prs)

**Review by KhesiweDube — APPROVED** [review]
Tested in qa filled in the Volunteer form as "New" It is working as [expected](https://docs.google.com/spreadsheets/d/1I2HC75gY-l5TqIXbzo-VfKzanSVD-gufedGZwkHEHKQ/edit?usp=sharing), The "I'm not sure"  is visible on the form and the teams are in alphabetic order.
When i'm on dashboard the team shows "Select team"  i cannot select "I am not sure" is team not visible on the dashboard.

765Test1

765Test2

Screenshot from 2023-09-21 18-17-23

Screenshot from 2023-09-21 18-13-02

**Comment by khmdagal** [comment]
> @khmdagal can you please make the PR title match the [ standards ](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#tips-to-create-good-prs)

@SaadiaELF  Thanks for the tips, I changed the title.

**Review by SaadiaELF — APPROVED** [review]
LGFM, I followed this steps :

1. Sign up as a new volunteer and filled out the form :  "I'm not sure" is visible on the form,  the the teams are in alphabetic order and "I am not sure" was on the bottom.

2. On the dashboard the team column show "Select team" and "I am not sure" is not visible

**Pull request merged**
