### PR TITLE
Change flags to show correct flags.

### PR DESCRIPTION
**Pull request by DavoodKhoshnood**
Before this change when user change country from phone number it couldn't find flag of country.

### CODE REVIEW

**Comment by DavoodKhoshnood** [comment]
Thanks for your response
I found that it missed the flags, I think we could switch the source instead.

**Comment by textbook** [comment]
Great, do you want to have a go at updating this PR?

**Comment by DavoodKhoshnood** [comment]
> Great, do you want to have a go at updating this PR?

Sure, I'll check and try to sort it out.

**Comment by DavoodKhoshnood** [comment]
It only needs to change the version of "react-phone-number-input" to "^3.2.6".

**Comment by textbook** [comment]
Ah I see we're using version 2. Can we upgrade to v3 without breaking anything? If not, does the old version not support the same (or a similar) functionality?

**Comment by textbook** [comment]
You have to look at the documentation _for the relevant version_. These things often change over time and it's changes to the interface, like renaming a prop or changing how it's used, that mean you need a new major version per [semver](https://semver.org/). 

- v2 README: https://github.com/catamphetamine/react-phone-number-input/tree/2.x#react-phone-number-input
- Changelog: https://github.com/catamphetamine/react-phone-number-input/blob/master/CHANGELOG.md

**Comment by textbook** [comment]
Upgrade [already committed to QA](https://github.com/CodeYourFuture/cyf-forms/commit/e54964f7053bdfc09a7111b1ef236675a75d70cc) and being reviewed for staging deployment in #101

**Pull request closed without merging**
